// <auto-generated />
using CadastroDeAluno.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroDeAluno.Migrations
{
	[DbContext(typeof(BancoContext))]
	partial class BancoContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("CadastroDeAluno.Models.AlunoModel", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

					b.Property<string>("Cep")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Cidade")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Cpf")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Email")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Endereco")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Estado")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Matricula")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Nacionalidade")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Nome")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Telefone")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("ALUNOS");
				});
			#pragma warning restore 612, 618

			//-----------------------------------------------------------------
			modelBuilder.Entity("CadastroDeAluno.Models.MateriaModel", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

				b.Property<string>("IdAluno")
					.IsRequired()
					.HasColumnType("varchar(50)");

				b.Property<string>("NomeMateria")
					.IsRequired()
					.HasColumnType("varchar(50)");

				b.Property<string>("QtdSemestre")
					.IsRequired()
					.HasColumnType("varchar(50)");

				b.HasKey("Id");

				b.ToTable("MATERIAS");
			});
			#pragma warning restore 612, 618

		}
	}
}
